language: cpp

os:
  - linux
  # - osx

compiler:
  - gcc
  - clang

# currently only builds via autotools
# will use the shared library of libsass
# - AUTOTOOLS=no COVERAGE=yes BUILD=shared
# - AUTOTOOLS=no COVERAGE=no BUILD=shared

env:
  - AUTOTOOLS=yes COVERAGE=yes BUILD=shared
  - AUTOTOOLS=yes COVERAGE=yes BUILD=static
  - AUTOTOOLS=no COVERAGE=yes BUILD=static
  - AUTOTOOLS=yes COVERAGE=no BUILD=shared
  - AUTOTOOLS=yes COVERAGE=no BUILD=static
  - AUTOTOOLS=no COVERAGE=no BUILD=static

# currenty there are various issues when
# built with coverage, clang and autotools

matrix:
  exclude:
    - compiler: clang
      env: AUTOTOOLS=yes COVERAGE=yes BUILD=shared
    - compiler: clang
      env: AUTOTOOLS=yes COVERAGE=yes BUILD=static

script: ./script/ci-build-libsass
before_install: ./script/ci-install-deps
install: ./script/ci-install-compiler
after_success: ./script/ci-report-coverage
